# Geral
key=quarkgps
appName=QuarkGPS
siteURL=https://rastrear.quarkgps.com
allowedHost=rastrear.quarkgps.com

# iOS
iosBundleId=com.quarkgps
iosMarketingVersion=2.0

# Android
androidApplicationId=com.quarkgps
androidVersionCode=24
androidVersionName=${androidVersionCode}.0
