# Geral
key=trackergpsrastreamento
appName=Tracker GPS Rastreamento
siteURL=https://rastreamento.trackergpsrastreamento.com/
allowedHost=rastreamento.trackergpsrastreamento.com

# iOS
iosBundleId=com.trackergpsrastreamento
iosMarketingVersion=1.0

# Android
androidApplicationId=com.trackergpsrastreamento
androidVersionCode=26
androidVersionName=${androidVersionCode}.0
