# Geral
key=rmrastreadores
appName=RM Rastreadores
siteURL=https://rastrear.rmrastreadores.com/
allowedHost=rastrear.rmrastreadores.com

# iOS
iosBundleId=com.rmrastreadores
iosMarketingVersion=1.0

# Android
androidApplicationId=com.rmrastreadores
androidVersionCode=1
androidVersionName=${androidVersionCode}.0
