key=auramonitoramento
appName=Aura Rastreamento
siteURL=https://auramonitoramento.com.br
allowedHost=auramonitoramento.com.br
iosBundleId=com.aurarastreamento
androidApplicationId=com.aurarastreamento
