# Geral
key=auramonitoramento
appName=Aura Rastreamento
siteURL=https://auramonitoramento.com.br
allowedHost=auramonitoramento.com.br

# iOS
iosBundleId=com.aurarastreamento
iosMarketingVersion=1.0

# Android
androidApplicationId=com.aurarastreamento
androidVersionCode=15
androidVersionName=${androidVersionCode}.0
